### ISSUE TITLE
Make it clear that this produces a javascript action which uses TypeScript

### ISSUE THREAD

**Issue by wesleytodd** [actions/typescript-action#15]
Just wondering if you have any interest in maintaining an actual JavaScript template?  The title of this repo is a bit miss-leading since it is typescript :)

**Comment by damccorm** [comment]
If we were to maintain a pure JavaScript template then I think I'd agree the title would be misleading/unhelpful, as it stands I think its best to leave the name for discoverability for people who are looking to build JavaScript actions since there's not a concept of TypeScript actions. So the JavaScript refers to the action type (JavaScript) more than how its being built (TypeScript), which I think is what people will look for.

That brings us to the first half of the question - do we plan on maintaining a pure JavaScript template. As of now, the answer is probably no - I don't see it adding a ton of value, especially since you can get that pretty easily by, building this, removing the TypeScript files, and updating the gitignore. In general, that's also consistent with our patterns in our tooling (e.g. the toolkit is written in TypeScript).

I'm not completely closed off to it, but I think I'd need help understanding the use case of why its helpful/better than this in some use cases, especially since adding it probably reduces the likelihood of people using this template.

**Comment by wesleytodd** [comment]
> If we were to maintain a pure JavaScript template then I think I'd agree the title would be misleading/unhelpful

Makes sense! I know I was surprised when I cloned this down that I had to remove most of the template to get "just js", but I agree that in essence it is the same form the platform support standpoint.

>  I don't see it adding a ton of value, especially since you can get that pretty easily by, building this, removing the TypeScript files, and updating the gitignore

This is what I did.  I am not sure the appetite for a pure JavaScript template, or what your considerations are for choosing what templates to maintain.  For me I will probably not be using this template because of it as it is more difficult to use than just running `npm init` and copying the `action.yml`.   But I guess I can see why you might choose to go this route from a maintenance perspective.

> since adding it probably reduces the likelihood of people using this template.

I will not be using this template, so I am not sure your logic holds up here, but that is for you to decide.  I try to keep an open mind in OSS and don't think I am "right", but if I were to put on my opinionated hat, I would say this:

Templates are examples, and examples are best when they are as simple as possible. By adding a toolchain and a whole new language to this template you increase the complexity your consumers need to understand it.  For advanced users this is less of an issue, but it still means those who want to write JavaScript are not able to use the template out of the box, which is an impediment.

So, all of this said, I will probably maintain my own template/scaffold/generator for JavaScript actions for now (as I plan on making quite a few).  If you think my feedback is valid then maybe we can collaborate and I can contribute my work back to the "official" templates.  If not I am happy to maintain the things I will use :)

**Comment by JasonEtco** [comment]
FWIW, I came to this repo to open an issue exactly like this. I think that, because TypeScript requires an extra build step and checking in those built files, it's one more point of difficulty for new folks building actions. It also isn't _necessary_ - totally agree that TS is a great language and ecosystem to build in, but JavaScript is (by the numbers) more popular and familiar, and doesn't require any compilation.

For a template designed for people who haven't written any actions before and don't know how it all works, simplicity is more important than anything else.

Might also be worth noting that [this walkthrough](https://github.com/actions/toolkit/blob/master/docs/javascript-action.md#publish-a-v1-release-action) doesn't even include information on compiling the TS (aside from listing `npm run build`).

> I don't see it adding a ton of value, especially since you can get that pretty easily by, building this, removing the TypeScript files, and updating the gitignore.

I agree with you that folks _can_ do this - but the first step in using a template shouldn't be removing half the dependencies and build steps. People should have what they need to start building and nothing more.

**Comment by damccorm** [comment]
@JasonEtco 

> For a template designed for people who haven't written any actions before and don't know how it all works, simplicity is more important than anything else.

Not sure I totally agree with this assumption - I think the most important thing is that people are able to write their actions as quickly/easily as possible, templates are just a means to that end. I know that's a subtle difference, but I would argue that some of the initial unfamiliarity/difficulty of TypeScript (which FWIW shouldn't seem **too** unfamiliar to a JavaScript dev) is offset by other advantages which will serve this larger goal. The ones I see right off the bat are:

- Our toolkit/first party actions are all written in TypeScript. That means plenty of examples of how to write good actions without an additional learning curve. Along with this, IMO it would be kinda weird to write all our first party actions in TypeScript because we think its a good pattern and then have our starter template do something else.
- TypeScript makes async/await a lot easier. That matters a lot because much of what we're doing in the toolkit (and presumably in 3rd party actions) uses async/await.

> the first step in using a template shouldn't be removing half the dependencies and build steps.

Sure - that wouldn't be my _recommended_ option 😄 was just pointing out that it _is_ an option

@wesleytodd 

I think I covered most of your feedback as well there, but was intrigued:

> So, all of this said, I will probably maintain my own template/scaffold/generator for JavaScript actions for now (as I plan on making quite a few).

Outside of a JS version of this template what would you plan on making?

______________

Overall, I appreciate the well thought out feedback from both of you ❤️ Even though I'm personally still leaning towards keeping this as is there's a lot of really good thoughts here that have helped me formulate a better idea of what purpose this repo should serve.

CC: @bryanmacfarlane @chrispat for any thoughts

**Comment by wesleytodd** [comment]
> Along with this, IMO it would be kinda weird to write all our first party actions in TypeScript because we think its a good pattern and then have our starter template do something else.

I think it is fine for your team to think this is a good pattern (it is also fine that I disagree). But, I would then argue that you should call this `typescript-template`.  You don't need to provide a JavaScript template, just be careful about this miss-leading name.

> Outside of a JS version of this template what would you plan on making?

I have ideas which are not ready to see the light :)  The first thing I have started is a Triage Action which will be used for Express project repos.  We have specific requirements and want to evolve it over time. This might mean having a set of actions, or having one with a bunch of behaviors, yet to be seen.

**Comment by JasonEtco** [comment]
Thank you both for sharing your thoughts here ❤️ @damccorm I really appreciate you being open to the feedback here ✨ 

> Sure - that wouldn't be my recommended option 😄 was just pointing out that it is an option

Sorry if I sounded pointed there! I just meant that since many people don't know TypeScript, it'd be hard for them to figure out what to remove and how.

> Our toolkit/first party actions are all written in TypeScript. That means plenty of examples of how to write good actions without an additional learning curve. Along with this, IMO it would be kinda weird to write all our first party actions in TypeScript because we think its a good pattern and then have our starter template do something else.

I get this - to be clear, I'm not suggesting that writing actions in TypeScript is a _bad_ option, I love TypeScript and I'm very happy to use it.

However, I don't think that it being an option is clear - folks have asked me if _JavaScript_ actions require _TypeScript_, and whether or not the intention is for that to be no, the perception (because of this repo's contents, and all the docs) is that the answer is yes (in my experience, from the people I've talked to about it).

And - I realize that TypeScript isn't a _huge_ departure from regular JS, but it is another thing to learn. Not every JavaScript dev knows TS, but every TS dev knows JS.

> TypeScript makes async/await a lot easier. That matters a lot because much of what we're doing in the toolkit (and presumably in 3rd party actions) uses async/await.

I'm not sure I understand this - JavaScript has had native async/await syntax as of Node.js 8, so maybe you're referring to something specific?

**Comment by wesleytodd** [comment]
> folks have asked me if JavaScript actions require TypeScript, and whether or not the intention is for that to be no, the perception (because of this repo's contents, and all the docs) is that the answer is yes

This is what I was worried about when opening the issue.  User confusion.

**Comment by bryanmacfarlane** [comment]
There are two types of actions that are supported (1) container and (2) javascript actions.  That is all that is supported at runtime.   The is no such thing as a typescript action.  Even this convenience repo template ends up producing a javascript action that is run as javascript as the workflow runs.

So the name is more about the type of action that is produced.

**Comment by wesleytodd** [comment]
> So the name is more about the type of action that is produced.

This is what I meant in my comment above when I said  "but I agree that in essence it is the same form the platform support standpoint."  That does not change the user confusion when they see this repo and it is TypeScript, leading to the "is TS required to build actions" question.

**Comment by bryanmacfarlane** [comment]
Thanks! I'll update the readme to make that clear.

**Comment by elstudio** [comment]
Now I say this as a fan of copy-and-paste 😄, but I strongly agree with @damccorm here: 

> By adding a toolchain and a whole new language to this template you increase the complexity your consumers need to understand it. For advanced users this is less of an issue, but it still means those who want to write JavaScript are not able to use the template out of the box, which is an impediment.

I know it’s early days, but our documentation for the actions/io and our other JS libraries is in JavaScript form, rather than TypeScript. Seems right to keep those consistent — for copy pasta purposes if nothing else.

Would you consider a modest pull request to convert this template to straight JS?

**Comment by bryanmacfarlane** [comment]
> documentation for the actions/io and our other JS libraries is in JavaScript form

Yep.  Makes sense.

If you build an action with javascript and the goal is to communicate how to get started (while avoiding all the other concepts like compile time, linting, test frameworks, etc.) then I agree 100%.  Case in point, the official docs which we're in PR are just npm install plus a javascript file.  

We're also going to add that javascript only getting started _documentation_ as the top link in the toolkit above the [current link to the template](https://github.com/actions/toolkit/blob/master/README.md#creating-an-action-with-the-toolkit)

However, what if you wanted to offer a template with it's very purpose being how to create an action with all those real world development problems (compile / static verification, linting, unit tests, publishing)?  At that point it's not documentation, it's a template which is what this is.

**Comment by wesleytodd** [comment]
> I strongly agree with ~~@damccorm~~ @wesleytodd  here:

;)

> However, what if you wanted to offer a template with it's very purpose being how to create an action with all those real world development problems (compile / static verification, linting, unit tests, publishing)? At that point it's not documentation, it's a template which is what this is.

> So the goal of the template is to offer everything you need to write and maintain a production action. Which a very different goal and topic than getting started copy past docs + npm install. That is very valuable as well on first approach.

I like both of these things, but JavaScript is *GREAT* for "real world development problems" and "everything you need to write and maintain a production action".

So I think the point is that your *opinion* is TypeScript is a good thing.  And it is fine for you to have this *opinion*.  But for people learning, beginners especially, also an advanced user who wants to understand the system, your templates *ARE DOCUMENTATION*.  Just saying the hand-wavy "real world" and "production" stuff doesn't really help either of these users.  

Having clear guides which show the actual minimum steps required does give the right start for the most good.  Having a typescript template for those who agree with your opinions is also a great idea, and I don't think anyone here is disagreeing with that existing, just that this naming is confusing and miss-leading.

**Comment by bryanmacfarlane** [comment]
@ethomson to consider.   I'm seriously considering a rename.

Quick question.  If we rename this to typescript, and the docs cover how to create from ground zero (we all agree a great thing), then would you see a purpose for a javascript-template?  The reason I ask is typescript is not the only opinionated way of working in this template.  And if you remove what's opinionated and go from ground zero (copy / paste code, npm install ...) then there's no need for a template.  That is unless it had publishing tooling and workflows etc...  I think that is fine to be opinionated about.

**History:** Just wanted to point out this wasn't about personal opinion.  The motivation was to package up how we (@github) created all our javascript tasks in the actions org and to package that up in a template (setup-node).  It actually started out as node12 and typescript but GitHub Actions branding was there are two types of actions, container and javascript and there was a branding.  And this one produced a javascript action.  

I ❤️ JS too :)

**Comment by wesleytodd** [comment]
> then would you see a purpose for a javascript-template? 

Well I do personally, because I would use it 😄.  There is more than just the TS opinions in this IMO.  Also, there is the "template for templates" part.  Using an un-opinionated base template as the start of a more opinionated one which I would actually use dat-to-day.  I like this approach and often use it for "scaffolding" type things because it is powerful.

> The motivation was to package up how we (@github) created all our javascript actions

I assumed this, which is why I thought it was important to separate opinions from requirements.  An outsider, like myself, cannot know without digging in deep, and not everyone is willing or has time to do that.

> I ❤️ JS too :)

🚀 ❤️ 🥇

**Comment by bryanmacfarlane** [comment]
Cool.  Any chance a bit more concrete on what would be in the javascript-template one without being opinionated? 😆

If I rename this, I will leave this for a little while then create a javascript one (redirects).  If I create I will start from bare bones and take PRs.  One thing we will eventually insist on is all the publishing workflows and tooling when we support GDR ...

**Comment by ethomson** [comment]
I’m in favor of a rename.  My concern is that if we have two versions that they could get out of sync, but I think that this is sufficiently simple to not be a big concern.  😀

**Comment by wesleytodd** [comment]
> what would be in the javascript-template one without being opinionated?

1. Readme with setup instructions
2. An `index.js` with the current `hello world`
3. `action.yaml` with example input (like currently exists)
4. The `checkin` workfow
5. Tests? (this one does contain an opinion on the test framework, but that is IMO a lower bar)

That list would provide value to me, enough value to justify using it IMO.

>  One thing we will eventually insist on is all the publishing workflows and tooling when we support GDR

I am not sure I am the target of this comment, but what is GDR?

**Comment by bryanmacfarlane** [comment]
Sorry, meant GPR (GitHub Package Registry).  We have plans to all consuming actions from GPR via a syntax in your workflow.  Thus eliminating the need to distribution branches.  So actions in repos with just code (long topic in itself).

I'm committing to doing this.  I'm off a couple days but next week, I'll dig into the feedback, the work and start making changes.  Give me a little time to work through the steps and details.

**Comment by bryanmacfarlane** [comment]
I got carried away and created this one tonight

https://github.com/actions/javascript-action

**Comment by bryanmacfarlane** [comment]
Done.  See ^^ for the js only version
