### ISSUE TITLE
Creating a branch produces lots of unwanted artifacts

### ISSUE THREAD

**Issue by JJ** [actions/typescript-action#18]
And besides, does not clarify workflow, which implies copying thing from master to branches and update them while debugging.

The documentation should clarify that the files needed are:
* action.yml 
* lib/main.js (or whatever file you're generating)
* package*.json
* Additionally, README.md and LICENSE, as well as a specific .gitignore.

**Comment by damccorm** [comment]
I think I disagree with this approach. The things you're taking out with that are:
- tests
- workflow files
- and typescript source files

These aren't really going to be significantly large in most use cases and it shouldn't cause problems to have them. The tradeoff is that you make the publishing process harder with more steps (which makes it more error prone and harder to automate), and you lose some readability (I like, for example, having the TypeScript files in the release since its easier for me to tell what's going on)

**Comment by JJ** [comment]
All that is in the master branch, or maybe a dev branch if you want to go that way. It's not so much about what is nice or not, but the minimum files necessary to make an action work. You can keep the rest if you want, but right now all files are replicated in release branches, up to and including a `docs/contributors.md` file... Knowing precisely what needs to be in a release branch gives you the ability to decide whether you want to keep the rest of the files or not.
And about workflow, it's very simple to create a commit hook that changes to the release branch and checks out lib/main.js from master every time you change it. No big deal.

**Comment by bryanmacfarlane** [comment]
What *must* be in the a branch that runs is the Actions.yml and the javascript file it references.  That's all.  The runner download the contents of that branch and run that entry point.

**Comment by bryanmacfarlane** [comment]
Closing since question answered.  We covered what's mandatory.  And yes, there's file in the distribution branch that are superfluous.  We are balancing complexity of this template, merges, etc vs optimizing what really isn't a problem (pulling a few text files at runtime)
