### ISSUE TITLE
Pre & post action setup without code duplication

### ISSUE THREAD

**Issue by lavaude** [actions/typescript-action#980]
Hi there,

This template repository is setup only for having one main ts script to run during the action.
However github actions support different hooks to run scripts before or after the workflow starts (for example preparation before, or clean up after)
Github docs: https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runspre

However, in this current template, if we set up one of this additional hook, the code is not transpiled in dist.

The issue https://github.com/actions/typescript-action/issues/811 suggests a modification of the package.json scripts to solve the transpilation of the hooks needed. For example:

package.json
```json
  "scripts": {
    ...
    "package:index": "npx ncc build src/index.ts -o dist/index --source-map --license licenses.txt && mv dist/index/index.js dist/ && rm -rf dist/index",
    "package:post": "npx ncc build src/cleanup.ts -o dist/post --source-map --license licenses.txt && mv dist/post/index.js dist/post/post.js && mv dist/post/post.js dist/cleanup.js && rm -rf dist/post",
    "package": "npm run package:index && npm run package:post",
    ...
  },
```

But when doing so, we end up in the "dist" folder with duplicated code. 
In my case, my js files for the main action and for the "post" script are both 42k lines with the exact same code...
So yes, it works, but this is definitely not an efficient packaging.

Would there be any better way to do so?

**Comment by ncalteen** [comment]
I did some testing on an ESM version of this action using `rollup` instead of `ncc` and seemed to have some better luck with it. I have a reproduction you can reference here: https://github.com/ncalteen/typescript-pre-post

At the moment, I will hold off adding this to this template repo until the ESM PR is reviewed, as it builds off that work. But in the short term the repo I linked has been set up so that the `main`, `pre`, and `post` steps are transpiled correctly (and there seems to be minimal code duplication between them).

A couple gotchas though to look out for:

- `\`pre\` execution is not supported for local action from './'`
  - If you are trying to test the action in a CI workflow, and calling it using `uses: ./`, you will most likely see this error since pre steps are not supported when calling the action "locally."
- Rollup is a bit picky about declaration maps and bundling multiple chunks. I'm not too sure of the right approach to ensure they are included, so I have removed them for now. Though personally, I don't see a huge benefit to them being included in the transpiled code.

**Comment by lavaude** [comment]
Thanks @ncalteen ! We gonna try rollup!

**Comment by ncalteen** [comment]
Sounds good!
